version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9228:4000"
      # - "9241:4000"

    environment:
      - DATABASE_URL_MAIN=mysql://root:50p4y5ky0v0!@8.215.44.147:3306/absensiDB
      - DATABASE_URL_SECONDARY=mysql://root:50p4y5ky0v0!@8.215.44.147:3306/db_skyccc
      - DATABASE_URL_THIRD=mysql://root:50p4y5ky0v0!@8.215.44.147:3306/skybillingdb
      - NODE_ENV=production
      - JWT_SECRET=158243e2-ccc0-4798-a944-2a5b0d1c90f3
      - SIGNATURE_SECRET=c719f771-69ce-4945-9895-1759fb49df87

    restart: always

    volumes:
      - ./uploads:/app/uploads
